reports:
  checkouts:
    title: "Checkouts Report"
    queries:
      - title:
        dict: 
          source: "$..book..title"
          target: "{'title': 'Checkouts Report', 'books': [{ 'title': ''}]}"
      - author:
        dict:
          source: "$..book..author"
          target: "{'title': 'Checkouts Report', 'books': [{ 'author': ''}]}"
      - price:
        dict:
          source: "$..book..price"
          target: "{'title': 'Checkouts Report', 'books': [{ 'price': ''}]}"